### ISSUE TITLE
The Notebook link is broken

### ISSUE THREAD

**Issue by DeepOceanDeep** [MadryLab/modeldiff#2]
Hi, the link https://github.com/MadryLab/modeldiff/tree/master/analysis  is not working. Leads to an error. 
Could you update it, please?

**Comment by harshays** [comment]
Hi @DeepOceanDeep, we restructured our code a while ago to add an API for ModelDiff. The analysis notebooks are now here: https://github.com/MadryLab/modeldiff/tree/master/notebooks.

**Comment by DeepOceanDeep** [comment]
Thanks @harshays
